### ISSUE TITLE
... needs options When will this be ready how can i help ?

### ISSUE THREAD

**Issue by Mako-L** [petecoop/phantasma#1]
... needs options When will this be ready how can i help , i nee proxy option for the phamtomjs instance just like in nightmare js :).

**Comment by petecoop** [comment]
Hey @MakoMakox yeah options are on the todo list! Just trying to finalize some other bits first then will add an options object with some defaults. I'll put some issues on here with a milestone to give some indication on what's left to do before 1.0

**Comment by Mako-L** [comment]
Thank you for the update. This is awesome!

**Comment by petecoop** [comment]
Hey no worries, working on the options next - I've updated the readme with the options I'll support to start with however haven't written the code to handle them yet! Maybe that will be done tonight!

**Comment by petecoop** [comment]
@MakoMakox I've added the options that are [described in the docs](https://github.com/petecoop/phantasma#new-phantasmaoptions). I'd be grateful if you could test your proxy settings and let me know the outcome, should work as it's passed the same way as nightmare
