### ISSUE TITLE
Having issues with proxy settings.

### ISSUE THREAD

**Issue by Mako-L** [petecoop/phantasma#12]
Phantasma doesn't connect with simple proxy 

``` javascript
var options = {
    proxy: '127.0.0.1:5000',
    proxyType: 'socks5'
};
var ph = new Phantasma(options);
```

When I try it with nightmare it works perfectly. Are there tests made for this option?
I love this library already it's much easier to use then nightmare (Good Job Guys!)

**Comment by petecoop** [comment]
Thanks will look into this. I think this needs to be a manual test really - I don't really want to set up a proxy server for testing.

Glad you like the library!

**Comment by petecoop** [comment]
I've just tested manually and it worked fine for me with the following code:

``` js
var options = {
  proxy: '127.0.0.1:5000',
  proxyType: 'socks5'
};

var ph = new Phantasma(options);

ph.open('http://www.whatsmyip.org/')
  .screenshot('screenshot.png')
  .finally(function () {
    console.log('done!');
    ph.exit();
  });
```

Screenshot shows the IP of my proxy server

**Comment by Mako-L** [comment]
Yes you are right, I'm sure I made a made a mistake at the proxy setup or something. Sorry for wasting your time ^_^.
