### ISSUE TITLE
When I get this error the ph process freezes .

### ISSUE THREAD

**Issue by Mako-L** [petecoop/phantasma#14]
When I get this error the ph process freezes .

``` JavaScript
phantom stdout: TypeError: 'null' is not an object (evaluating 'ele.dispatchEven
t')


phantom stdout:   phantomjs://webpage.evaluate():5
  phantomjs://webpage.evaluate():6
  phantomjs://webpage.evaluate():6
```

**Comment by Mako-L** [comment]
Fixed the bug in my code. But still I don't understand why it freezes when phantom gets a 'null' error.

**Comment by petecoop** [comment]
What do you mean by freezes? Is this error uncaught or is the error coming through to a `.catch` method?

**Comment by Mako-L** [comment]
It was an uncaught error, but I managed to fix it ^_^. I will try to test more before posting issues from now on.
