### ISSUE TITLE
Not terminated phantasma

### ISSUE THREAD

**Issue by imjuni** [petecoop/phantasma#19]
Good code, thank. I found from nightmare issue tracker.

I was parallel execution phantasma using generator. In this case, phantasma not complete.

upload test code from https://github.com/imjuni/phantatest.git

my environment below,
io.js 2.2.1
phantomjs 1.9.8
phantasma 1.1.2
co 4.5.4

thx

**Comment by petecoop** [comment]
It doesn't look like you are resolving your promise, where does it get up to?

**Comment by imjuni** [comment]
@petecoop you right, so I add resolve function call at finally. But same, not terminated. I was upload new code same repo.

**Comment by petecoop** [comment]
have replicated the issue, looking into a fix

**Comment by petecoop** [comment]
I know it's been a while, but I've just created a fix for this and published as 1.3.0
