### ISSUE TITLE
Tasks on same phantom instance.

### ISSUE THREAD

**Issue by Mako-L** [petecoop/phantasma#23]
I'm looking to create a function that ads tasks to the same ph instance and waits for each task to finish.
Like 

``` javascript
var tasks = [](array of functions on same ph instance)
var login = function(user,pass,tasks){}
```

Or to create a function that keeps an instance alive for unlimited time and another functions that passes tasks to the main one. There should be a functions that handles the requests from the adding(tasks) one.

Do you guys have some advices how should I proceed?

**Comment by petecoop** [comment]
the instance is kept alive for as long as you want, I think you want to read up on promises but you could easily do something like:

``` js
var ph = new Phantasma();

var tasks = [];

Promise.all(tasks)
  .then(function ()){
    //login
  });
```

Really depends what you want to do but Promises make this really easy

**Comment by Mako-L** [comment]
*I over complicated myself with this solution.

**Comment by Mako-L** [comment]
EDIT: I fixed the error, Thank you so much for the help.
I get this error : 

``` javascript
error { [TimeoutError: operation timed out]
  stack:
   [ { _fileName: 'node.js',
       _functionName: 'unknown',
       _lineNumber: 51,
       _columnNumber: 16,
       _msg: '    at SubError@C:\\Workplace\\node_modules\\phantasma\\node_modul
es\\bluebird\\js\\main\\errors.js:15:13' },
     { _fileName: 'node.js',
       _functionName: 'unknown',
       _lineNumber: 51,
       _columnNumber: 16,
       _msg: '    at module.exports/afterTimeout@C:\\Workplace\\node_modules\\ph
antasma\\node_modules\\bluebird\\js\\main\\timers.js:11:15' },
     { _fileName: 'node.js',
       _functionName: 'unknown',
       _lineNumber: 51,
       _columnNumber: 16,
       _msg: '    at timeoutTimeout@C:\\Workplace\\node_modules\\phantasma\\node
_modules\\bluebird\\js\\main\\timers.js:53:9' },
     { _fileName: 'timers.js',
       _functionName: 'listOnTimeout',
       _lineNumber: '112',
       _columnNumber: '9',
       _msg: '    at listOnTimeout@timers.js:112:9' },
     { _fileName: 'node.js',
       _functionName: 'unknown',
       _lineNumber: 51,
       _columnNumber: 16,
       _msg: '    at ' },
     toString: [Function] ],
  fileName: 'node.js',
  lineNumber: 51,
  columnNumber: 16 }
done! :6

```

The screen shots don't even appear :(  .
Can you help me figure this out? :+1: 
Thanks anticipated :100:

**Comment by petecoop** [comment]
Don't do a `.wait()` after `.open()` it's not necessary.

`.url()` returns a promise - it doesn't take a callback argument e.g.

``` js
.url()
.then(function (url) {
  console.log(url)
});
```

**Comment by Mako-L** [comment]
I'm thinking that a function that handles multiple Phantom instances and also promises might come in handy . It would be great if we could implement a status for the operations so that we can get live updates on what is the progress of the tasks. How should I start?
How do I get access to the Promise.all object?
Some guiding thoughts that could send me in the right direction, would be awesome!
I'll start right away ^_^

**Comment by petecoop** [comment]
Hmm not sure on getting some live updates of the tasks - other than adding some debug option that console.log's some debugging messages, that the kind of thing you're after? Would just be a case of adding some logging to each method if the option is true.

Promise.all is part of Bluebird, I think it would be worth you reading up on it: https://github.com/petkaantonov/bluebird/blob/master/API.md

**Comment by Mako-L** [comment]
Let's say if you and I build a website where people write their own functionalities for the website and we had a panel where they can build the tests with simple drag and drop features. I would have to have a server that receives the task requests and adds them to their own/specific 'ph' instance. 
An ph instance can open a single tab and use it or it can open multiple tabs and run them synchronously. 
After that part is ready I would have to build an class that handles the multi-Ph-Instances .
Any recommendations ^_^

**Comment by petecoop** [comment]
Ah i see, you'd probably just want to store the instances in an object e.g.

```
var instances = {};

var ph = new Phantasma();
instances['example.com'] = ph;
```

Or replace `'example.com'` with their ID if using a database with it
