### ISSUE TITLE
Multiple phantasma/phantom processes

### ISSUE THREAD

**Issue by gizmodude4** [petecoop/phantasma#26]
Hi there!

First off, great project. I've been using it for the past three months and it's worked out great. It's about time to start putting this thing in production and I'm running in to a bit of an issue.

I have an express server sitting in front of my phantasma stuff so that every time I get a request, I try to create a new phantasma object to work on using this:

 `var phantasma = new Phantasma({'timeout':120000, 'load-images':false, 'proxy':proxy});`

I thought this would be fine since each request should be using its own phantasma object, but I'm getting the following error quite often:

`Unhandled rejection Error: tried to open before page created`

It seems like it may be trying to use the same phantom process for each of the jobs. I've tried specifying a random port number in hopes that when calling `phantom.create`, the different port numbers would spawn different processes, but that didn't work.

Do you have any insight in to this or how I can explicitly separate each of these jobs? Thanks!

**Comment by petecoop** [comment]
Hey can you provide a sample of code?

**Comment by gizmodude4** [comment]
From the express part of my code:

<pre><code>app.get('/job/execute', function(req, res){
  // Node.js has a default http timeout of 2 minutes
  // for every request. We set it to 1 hour here.
  res.setTimeout(60 * 60 * 1000);
  // Make sure that all parameters are present and in the
  // correct form.
  isvalid(req.query,{
    'proxy_address': {type: String, required: true},
    'proxy_port': {type: Number, required: true},
    'username': {type: String, required: true}
  }, function(err, validData){
    // If error is set, query is invalid due to either
    // type mismatch or missing params
    if (err){
      res.status(400).send({'status':'failure','message':err});
    } else {
      Job.execute(function(statusCode, response){
        res.status(statusCode).send(response);
      }, validData);
    }
  });
});</code></pre>

And from the Job part:

<pre><code>function (responseCb, jobDetails){
    var proxy = jobDetails.proxy_address + ':' + jobDetails.proxy_port;
    var phantasma = new Phantasma({'timeout':120000, 'load-images':false, 'proxy':proxy});
    phantasma
      .pageSetting('userAgent', 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36')
      .viewport(1024, 768)
      .on('onError',function(msg, trace){
        var msgStack = ['PHANTOM ERROR: ' + msg];
        if (trace && trace.length) {
          msgStack.push('TRACE:');
          trace.forEach(function(t) {
            msgStack.push(' -> ' + (t.file || t.sourceURL) + ': ' + t.line + (t.function ? ' (in function ' + t.function +')' : ''));
          });
        }
        var stackTrace = msgStack.join('\n');
        console.error(stackTrace);
        phantasma.exit();
        responseCb(500, {'status':'failure', 'message':stackTrace});
      });
      var job = new ParticularJob(phantasma);
      job.execute(passedCb, failedCb);</code></pre>

When I hit the /job/execute URL once, a phantomjs process gets kicked off and everything starts working fine. If I hit that URL again while that first job is still executing, I see a new process spawn, but URLs won't open anymore. From my onError above, I often get this:

`[500] : {"status":"failure","message":"PHANTOM ERROR: TypeError: null is not an object (evaluating 'document.querySelector(selector).focus')\nTRACE:\n -> phantomjs://webpage.evaluate(): 2\n -> phantomjs://webpage.evaluate(): 3"}`

**Comment by gizmodude4** [comment]
I've come up with a far simpler example for this after a lot of digging. It seems that each new Phantasma instance spawns a new phantomjs process, but only ever keeps track of the most recently spawned one. The test I did for this is as follows:

```
var Phantasma = require('phantasma');

var phantasma1 = new Phantasma();
phantasma1.then(function(){
  console.log('phantasma1 pid: ' + phantasma1.getPid());
  var phantasma2 = new Phantasma();
  phantasma2.then(function(){
    console.log('phantasma1 pid: ' + phantasma1.getPid());
    console.log('phantasma2 pid: ' + phantasma2.getPid());
  })
});
```

Where I added a function to Phantasma called getPid, which looks like this:

```
Phantasma.prototype.getPid = function () {
  var self = this;

  if (self.ph){
    return self.ph.process.pid;
  }
  return null;
}
```

Is there something flawed with my test, or am I seeing this right?

**Comment by petecoop** [comment]
Thanks, I'll look into this in some more detail

**Comment by petecoop** [comment]
Interesting, this worked for me. I've created a test and opened a PR #31

**Comment by petecoop** [comment]
Hang on nvm I got that wrong, set up #31 properly

**Comment by gizmodude4** [comment]
Maybe this has something to do with it?

http://stackoverflow.com/questions/13611752/javascript-module-pattern-vs-constructor-with-methods-defined-in-constructor

It could be that every time we call new Phantasma(), instead of getting a new Phantasma, we're getting the same static Phantasma variable over and over again

**Comment by petecoop** [comment]
Found the issue. Sort of the right thing yeah - because of how I've wrapped Phantasma behind Bluebird's promise - I'm extending the promise to retrieve the instance of Phantasma. Simply moving the instantiation of the promise into the promise function fixed it

**Comment by petecoop** [comment]
I've published the fix as 1.3.0. Can you please have a try and let me know how you get on

**Comment by gizmodude4** [comment]
Looks good to me! Thanks so much for the really fast turnaround

**Comment by petecoop** [comment]
Great! No worries, thanks for doing that bit of digging
