### ISSUE TITLE
Custom phantom path not observed

### ISSUE THREAD

**Issue by w33ble** [petecoop/phantasma#27]
The options passed in to the new phantasma instance includes a `phantomPath` param which is supposed to allow users to specify a custom Phantom install location. This setting is passed directly to [sgentle/phantomjs-node](https://github.com/sgentle/phantomjs-node).

However, that library doesn't use that param, but instead uses `path` (and `binary` as well), [as you can see here](https://github.com/sgentle/phantomjs-node/blob/master/phantom.coffee#L54-L58)

```
options.path ?= ''
options.binary ?= options.path+'phantomjs'
options.port ?= 0
options.hostname ?= 'localhost'
options.dnodeOpts ?= {}
```

I propose the following:
- removing `phantomPath` from the options since it doesn't appear to be used at all
- adding `path` and `binary` to the options

It's a simple change, and I'm happy to make a PR for it if this seems like the right solution.

**Comment by petecoop** [comment]
Yeah makes sense, I can't remember where I got `phantomPath` from but it must have been somewhere... happy for you to make a PR for this

**Comment by w33ble** [comment]
It's possible that it used to use `phantomPath`, I poked through the history on that file a little, but gave up quick since it didn't really matter much ;)

PR forthcoming...

**Comment by petecoop** [comment]
Yeah I had a little look too but couldn't find anything useful, thanks!

**Comment by w33ble** [comment]
I just noticed that [horseman](https://github.com/johntitus/node-horseman#installation) uses `phantomPath` for that setting. Perhaps that's where you got your inspiration? ;)

**Comment by petecoop** [comment]
yeah probably, I stole code from there and nightmare :P
