### ISSUE TITLE
How to click the rect with position ?

### ISSUE THREAD

**Issue by chouchou900822** [petecoop/phantasma#30]
In phantomjs, I can click the element rect with the position.

``` js
var rect = page.evaluate(function () {
      return $('h3:contains("foo")')[0].getBoundingClientRect();
    });

page.sendEvent('click', rect.left + rect.width / 2, rect.top + rect.height / 2);
```

How should I do this with phantasma ?

**Comment by petecoop** [comment]
Is there any reason you can't just directly click the element you are looking for?

e.g.

``` js
.evaluate(function () {
  return $('h3:contains("foo")')[0].click();
});
```

**Comment by chouchou900822** [comment]
Sometimes there are two many elements I don't know which one bind the click event, so I want to click the rect instead of element to trigger the event.

**Comment by petecoop** [comment]
Did you find a solution? I've just had a bit more of a look - you can use the same sendEvent function like this:

``` js
var ph = new Phantasma();
// ...
.evaluate(function () {
  return $('h3:contains("foo")')[0].getBoundingClientRect();
})
.then(function (rect) {
  return ph.page.sendEvent('click', rect.left + rect.width / 2, rect.top + rect.height / 2);
})
```

This is used in the `type()` method internally here: https://github.com/petecoop/phantasma/blob/master/index.js#L229

**Comment by chouchou900822** [comment]
``` js
var ph = new Phantasma();
ph.page.sendEvent;// error: Cannot read property 'sendEvent' of undefined
```

This ph's page is undefined.
So I add this function in the prototype.

``` js
Phantasma.prototype.clickRect = function (rect) {
  var self = this;
  return new this.promise(function (resolve, reject) {
     self.page.sendEvent('click', rect.left + rect.width / 2, rect.top + rect.height / 2);
    resolve();
    }).wait();
};

var ph = new Phantasma();
// ...
ph.clickRect(rect)
```

It works for me now, THX!

**Comment by petecoop** [comment]
Great. I'm thinking about overloading `.click()` so that `.click(x, y)` will use this method, what do you think?

**Comment by petecoop** [comment]
By the way - using `.wait()` there would mean clicking the element must result in loading a new page

**Comment by chouchou900822** [comment]
Well, it's easy to use, and can be used in more cases.

**Comment by petecoop** [comment]
have added `.click(x, y)`. Will publish soon.
