### ISSUE TITLE
Phantom path

### ISSUE THREAD

**Issue by gizmodude4** [petecoop/phantasma#35]
It looks like Phantasma isn't forwarding the binary location on to PhantomJS. I modified PhantomJS to print out the binary location. This for loop doesn't actually do anything with `phantomPath`. I modified it to manually take in phantomPath, but this definitely won't work if I haven't specified anything.

```
for(var o in this.options){
    if(this.options[o] !== null){
      if(OPTIONS.params.indexOf(o) !== -1){
        options.parameters[changeCase.paramCase(o)] = this.options[o];
      }
      if(OPTIONS.options.indexOf(o) !== -1){
        options[o] = this.options[o];
      }
      if(OPTIONS.page.indexOf(o) !== -1){
        pageOptions[o] = this.options[o];
      }
    }
  }
  options['binary'] = this.options['phantomPath'];
```

Any ideas?

**Comment by gizmodude4** [comment]
Ah, I was using `phantomPath` when I should have been using `binary`

**Comment by petecoop** [comment]
@gizmodude4 is this something that should be cleared up in the docs at all?

**Comment by gizmodude4** [comment]
I'd say so. You have `phantomPath` listed as the property for that, but it doesn't work. `binary` does though

**Comment by petecoop** [comment]
Yeah I see, I've updated it
