### ISSUE TITLE
XMLHttpRequest Exception 101

### ISSUE THREAD

**Issue by hugocar** [petecoop/phantasma#37]
Hi,

I did a fresh install of phantasma, tried the first exemple and got this error :

`phantom stdout: NETWORK_ERR: XMLHttpRequest Exception 101: A network error occurred in synchronous requests.`

Any idea on how I can solve this

**Comment by hugocar** [comment]
Setting `web-security` at `false` solved the issue

**Comment by JediMindtrick** [comment]
Came here looking at this exact same issue and like original poster answered webSecurity: false "fixed" the problem.  The only problem is that I'm looking at using this with aws lambda and I'm not sure why this "fix" works.  I'm concerned that this will not be acceptable to do up on aws.  

So does anyone know why this happens?
