### ISSUE TITLE
Trouble with running example code

### ISSUE THREAD

**Issue by Mako-L** [petecoop/phantasma#38]
I get this error when I try to run the example code:

`phantom stdout: NETWORK_ERR: XMLHttpRequest Exception 101: A network error occurred in synchronous requests.phantom stdout:   phantomjs://code/shim.js:1815 in sendphantom stdout:   phantomjs://code/shim.js:1815 in _startphantom stdout:   phantomjs://code/shim.js:1842`

I think it needs to be updated with the new phantomjs 2.0 or something.
Can somebody help?

**Comment by petecoop** [comment]
have a look at #37

**Comment by Mako-L** [comment]
It worked thank you. I'll use it as it is.
